sudo: false
language: python
python:
      - "3.5"
install:
      - pip install tox 
script:
      - tox
env:
      - TOXENV=py27
      - TOXENV=py34
      - TOXENV=py35
      - TOXENV=pypy
      - TOXENV=pep8
      - TOXENV=functional
      - TOXENV=py35-functional
      - TOXENV=py34-functional
